# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-27 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0003_trip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='my_trip',
            new_name='created_by',
        ),
    ]
