# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-27 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_app', '0004_auto_20171227_0320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='travelfrom',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='travelto',
            field=models.DateTimeField(),
        ),
    ]
